### ISSUE TITLE
ARCHETYPE_HRID is missing fields

### ISSUE THREAD

**Issue by pieterbos** [openEHR/specifications-ITS-BMM#11]
ARCHETYPE_HRID does not have the following fields in BMM, but it does in AOM2:

concept_id
version_status
namespace
rm_publisher
rm_class
release_version
build_count
rm_package

In addition, the BMM spec says ARCHETYPE_HRID inherits from OBJECT_ID, including a value attribute. the AOM2 spec says otherwise.

Also i'm not sure why this type is included in BASE since in the spec it's part of AOM2, not BASE.

**Comment by wolandscat** [comment]
It will have to move to BASE, because it is needed by PROC and probably some other packages in the future - anywhere you want to mention an archetype id.
