### ISSUE TITLE
BMM 1.0.4: DV_QUANTITY.property is mandatory, but does not exist in spec

### ISSUE THREAD

**Issue by pieterbos** [openEHR/specifications-ITS-BMM#8]
I understand why DV_QUANTITY.property is in the BMM. However, maybe it should not be mandatory, given that it's not actually a property in the RM in the specifications.

**Comment by wolandscat** [comment]
Yes, in theory this has to be removed, but at the moment, a lot of old archetypes assume this property, and if the BMM is used in an archetype tool (e.g. ADL-designer), those archetypes will fail if this property is not there. We need to get these archetypes fixed...

**Comment by pieterbos** [comment]
Perhaps then it should be an optional property of a dv_quantity and not a mandatory one in the bmm...

**Comment by wolandscat** [comment]
Yep, I'll fix that in the various RM BMMs.
